### ISSUE TITLE
Crash on restart with quick start open

### ISSUE THREAD

**Issue by pvginkel** [TQLApp/TQL#123]

**Comment by pvginkel** [comment]
```
2023-11-29T14:43:38.2476705+01:00	CRIT	[Tql.App.App]	[0]	Unhandled dispatcher exceptionSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Tql.App.QuickStart.QuickStartManager.<>c__DisplayClass9_0.<Show>b__7(Object s, EventArgs _) in D:\a\TQL\TQL\Tql.App\QuickStart\QuickStartManager.cs:line 126
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
